### ISSUE TITLE
Historias de Usuario

### ISSUE THREAD

**Issue by jegarzonpa** [jegarzonpa/Proyecto_TransAPP#4]

**Comment by jjordan08** [comment]
Se realiza actualizacion sobre la actualizacion de las historias de usuario que se tenian, debido a que se cambia el alcance en referencia a los usiarios, debido a que va a ser solo un tipo de usuario con todas las funcionalidades

**Comment by jjordan08** [comment]
se tienen las historias de usuario completas, sin embargo se dejan congeladas en caso de encontrar algún requerimiento  nuevo que se deba agregar
