### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by jegarzonpa** [jegarzonpa/Proyecto_TransAPP#6]
Se crea el caso para la creación de los mockups, los cuales estarán en el repositorio de la aplicación en el GitHub

**Comment by jjordan08** [comment]
se realizo el avance de los mock ups en donde se evidencia la falta de una base de datos sobre las imagenes y preguntas

**Comment by jjordan08** [comment]
los muckups se encuentran finalizados en donde se ven las diferentes vistas

**Comment by jjordan08** [comment]
los mock ups fueron finalizados y se hace implementacion de estos en la app
